In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [2]:
input_size =5
output_size =2
batch_size =30
data_size = 100

In [3]:
class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
        
    def __getitem__(self, index):
        return self.data[index]
    
    def __len__(self):
        return self.len
    
rand_loader = DataLoader(dataset=RandomDataset(input_size, data_size), batch_size=batch_size, shuffle=True)

In [4]:
class Model(nn.Module):
    
    def __init__(self, input_size, output_size):
        super(Model, self).__init__()
        self.fc = nn.Linear(input_size, output_size)
        
    def forward(self, input):
        output = self.fc(input)
        print("\tIn Model: input size", input.size(), "output size", output.size())
        
        return output

In [5]:
model = Model(input_size, output_size)
if torch.cuda.device_count() > 1:
    print("Let's use", torch.cuda.device_count(), "GPUs!")
    model = nn.DataParallel(model)

Let's use 4 GPUs!


In [6]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
#device = torch.device("cpu")

model.to(device)

DataParallel(
  (module): Model(
    (fc): Linear(in_features=5, out_features=2, bias=True)
  )
)

In [7]:
for data in rand_loader:
    input = data.to(device)
    output = model(input)
    print("Outside: input size", input.size(), "output_size", output.size())

	In Model: input size torch.Size([8, 5]) output size torch.Size([8, 2])
	In Model: input size torch.Size([8, 5]) output size torch.Size([8, 2])
	In Model: input size torch.Size([8, 5]) output size torch.Size([8, 2])
	In Model: input size torch.Size([6, 5]) output size torch.Size([6, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
	In Model: input size	In Model: input size	In Model: input size torch.Size([8, 5]) output size torch.Size([8, 2]) torch.Size([8, 5]) output size torch.Size([8, 2])
 
torch.Size([8, 5]) output size torch.Size([8, 2])
	In Model: input size torch.Size([6, 5]) output size torch.Size([6, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
	In Model: input size	In Model: input size	In Model: input size   torch.Size([8, 5]) output size torch.Size([8, 2])
torch.Size([8, 5]) output size torch.Size([8, 2])
torch.Size([8, 5])	In Model: input size output size  torch.Size([8, 2])
torch.Size([6, 5]) output size torch.Size(

In [83]:
import torch
a = torch.rand(10, 1)
b = torch.rand(10, 1)

In [17]:
a[:] += b[:]

In [18]:
a

tensor([[1.1079],
        [0.1695],
        [1.0704],
        [1.1537],
        [1.2025],
        [0.9523],
        [0.6028],
        [1.0524],
        [0.9213],
        [0.7039]])

In [36]:
import logging

In [37]:
logging.basicConfig(
    level=logging.INFO, 
    format = '%(asctime)s:%(levelname)s:%(message)s',
    datefmt = '%m/%d/%Y %H:%M:%S.%s'
)

In [62]:
def f(*value):
    print(' '.join(map(str, value)))

In [31]:
import torch

In [32]:
data = torch.Tensor([1,2,3,4])

In [33]:
torch.std_mean(data)

(tensor(1.2910), tensor(2.5000))

In [34]:
(1+2+3+4) / 4

2.5

In [38]:
a = data - 2.5

In [39]:
a

tensor([-1.5000, -0.5000,  0.5000,  1.5000])

In [41]:
torch.mean(torch.abs(a))

tensor(1.)

In [42]:
import time

In [44]:
time.strftime('%Y%m%d_%H%M%S', time.localtime(time.time()))

'20210425_203219'

In [47]:
rank = 2

In [108]:
import math

In [113]:
input = torch.Tensor([1,2,3,10]).cuda()

In [121]:
a, b  = torch.std_mean(input)

In [122]:
a

tensor(4.0825, device='cuda:0')

In [123]:
b

tensor(4., device='cuda:0')

In [119]:
torch.sum(torch.pow(input - 4, 2)) /  3

tensor(16.6667, device='cuda:0')

In [125]:
torch.sqrt(torch.mean(torch.pow(input - 4,2)))

tensor(3.5355, device='cuda:0')

In [120]:
a, b = torch.sqrt(torch.mean(torch.pow(input - 2.5,2)))

TypeError: iteration over a 0-d tensor

In [91]:
torch.sqrt(torch.pow(input - 2.5,2))

tensor([1.5000, 0.5000, 0.5000, 1.5000], device='cuda:0')

In [90]:
torch.mean(torch.sqrt(torch.pow(input - 2.5,2)))

tensor(1., device='cuda:0')

In [76]:
math.sqrt(math.pow(input - 2.5, 2))

ValueError: only one element tensors can be converted to Python scalars

In [63]:
math.sqrt(math.pow(3,2))

3.0

In [ ]:
torch.std_mean